<a href="https://colab.research.google.com/github/Kzis/BADS4002/blob/master/pca-iris-dataset2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np  
import pandas as pd 

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"  
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']  
dataset = pd.read_csv(url, names=names)  

dataset.head()  

sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [9]:
X = dataset.drop('Class', 1)  
y = dataset['Class']  

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)  
print(X_train)
# print(X_test)
# print(y_train)
# print(y_test)

     sepal-length  sepal-width  petal-length  petal-width
137           6.4          3.1           5.5          1.8
84            5.4          3.0           4.5          1.5
27            5.2          3.5           1.5          0.2
127           6.1          3.0           4.9          1.8
132           6.4          2.8           5.6          2.2
59            5.2          2.7           3.9          1.4
18            5.7          3.8           1.7          0.3
83            6.0          2.7           5.1          1.6
61            5.9          3.0           4.2          1.5
92            5.8          2.6           4.0          1.2
112           6.8          3.0           5.5          2.1
2             4.7          3.2           1.3          0.2
141           6.9          3.1           5.1          2.3
43            5.0          3.5           1.6          0.6
10            5.4          3.7           1.5          0.2
60            5.0          2.0           3.5          1.0
116           

In [10]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()  
X_train = sc.fit_transform(X_train)  
X_test = sc.transform(X_test)  

X_train

array([[ 0.61303014,  0.10850105,  0.94751783,  0.73603967],
       [-0.56776627, -0.12400121,  0.38491447,  0.34808318],
       [-0.80392556,  1.03851009, -1.30289562, -1.3330616 ],
       [ 0.25879121, -0.12400121,  0.60995581,  0.73603967],
       [ 0.61303014, -0.58900572,  1.00377816,  1.25331499],
       [-0.80392556, -0.82150798,  0.04735245,  0.21876435],
       [-0.21352735,  1.73601687, -1.19037495, -1.20374277],
       [ 0.14071157, -0.82150798,  0.72247648,  0.47740201],
       [ 0.02263193, -0.12400121,  0.21613346,  0.34808318],
       [-0.09544771, -1.05401024,  0.10361279, -0.03987331],
       [ 1.0853487 , -0.12400121,  0.94751783,  1.12399616],
       [-1.39432376,  0.34100331, -1.41541629, -1.3330616 ],
       [ 1.20342834,  0.10850105,  0.72247648,  1.38263382],
       [-1.04008484,  1.03851009, -1.24663528, -0.81578628],
       [-0.56776627,  1.50351461, -1.30289562, -1.3330616 ],
       [-1.04008484, -2.4490238 , -0.1776889 , -0.29851096],
       [ 0.73110978, -0.

In [11]:
from sklearn.decomposition import PCA

pca = PCA()  
X_train = pca.fit_transform(X_train)  
X_test = pca.transform(X_test) 

X_train

array([[ 1.27228206e+00,  3.57878727e-01,  1.80336960e-01,
        -2.18683823e-01],
       [ 1.52231770e-01, -2.99835283e-01,  6.57129626e-01,
        -2.49320747e-01],
       [-2.18764183e+00,  6.17154256e-01, -1.80887051e-01,
         3.66971080e-03],
       [ 9.41913396e-01,  1.21810481e-02,  3.29616253e-01,
        -1.23928051e-02],
       [ 1.76227837e+00, -2.71066387e-01,  3.36678920e-01,
         9.29947613e-02],
       [-8.16806401e-02, -1.04319475e+00,  5.24835677e-01,
        -2.98705715e-02],
       [-1.89794863e+00,  1.48464927e+00, -3.40792097e-01,
         5.29711669e-02],
       [ 9.59395493e-01, -6.91087802e-01,  9.92861246e-02,
        -1.91468714e-01],
       [ 3.65661204e-01, -9.13013087e-02,  2.01390351e-01,
         3.40875107e-02],
       [ 2.31845912e-01, -1.01891237e+00, -2.00913311e-01,
        -8.50013948e-03],
       [ 1.79730127e+00,  3.25092688e-01,  1.91532698e-02,
         1.34801794e-01],
       [-2.40350676e+00, -2.44874760e-01,  5.92229980e-02,
      

In [12]:
explained_variance = pca.explained_variance_ratio_  
explained_variance

array([0.72226528, 0.23974795, 0.03338117, 0.0046056 ])

In [13]:
from sklearn.decomposition import PCA

pca = PCA(n_components=1)  
X_train = pca.fit_transform(X_train)  
X_test = pca.transform(X_test) 

X_train

array([[ 1.27228206e+00],
       [ 1.52231770e-01],
       [-2.18764183e+00],
       [ 9.41913396e-01],
       [ 1.76227837e+00],
       [-8.16806401e-02],
       [-1.89794863e+00],
       [ 9.59395493e-01],
       [ 3.65661204e-01],
       [ 2.31845912e-01],
       [ 1.79730127e+00],
       [-2.40350676e+00],
       [ 1.82199968e+00],
       [-1.98427118e+00],
       [-2.17073306e+00],
       [-2.55598076e-01],
       [ 1.38862320e+00],
       [ 1.93409268e+00],
       [ 1.12243099e+00],
       [ 1.88169499e+00],
       [ 5.43123767e-02],
       [ 2.70365641e+00],
       [ 6.91516012e-01],
       [ 1.30048660e-02],
       [ 1.22853905e+00],
       [ 1.01881714e+00],
       [ 2.57616370e-01],
       [ 1.44310720e+00],
       [ 1.03458720e+00],
       [ 1.43772035e+00],
       [ 3.84673096e-01],
       [-2.18860624e+00],
       [ 1.05608476e+00],
       [ 1.92641524e-01],
       [-1.12363985e-01],
       [ 1.72424265e-01],
       [ 5.48040969e-01],
       [ 1.88178641e+00],
       [-2.2

In [14]:
explained_variance = pca.explained_variance_ratio_  
explained_variance

array([0.72226528])

In [15]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(max_depth=2, random_state=0)  
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)  

y_pred

array(['Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa'], dtype=object)

In [18]:
from sklearn.metrics import confusion_matrix  
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)  
print(cm)  
print('Accuracy ' + str(accuracy_score(y_test, y_pred))) 

[[11  0  0]
 [ 0 12  1]
 [ 0  1  5]]
Accuracy 0.9333333333333333
