<a href="https://colab.research.google.com/github/Kzis/BADS4002/blob/master/pca.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

dataset = pd.read_csv('AirBNB_Taipei_listings_clean_missing.csv')

dataset.head()

id  accommodates  bathrooms  bedrooms  beds  price  guests_included  \
0   68396             2        1.0         1     1   1523                2   
1   68398             2        1.0         1     1    914                1   
2   74641             3        1.0         1     1   1523                1   
3   74643             2        1.0         1     1   1279                1   
4  178036             4        4.0         1     4    396                1   

   extra_people  minimum_nights  maximum_nights  availability_30  \
0             0               7             365                0   
1             0              30             365                0   
2           244               2             365               18   
3           244               1             365               22   
4           350               1              90               26   

   availability_60  availability_90  availability_365  number_of_reviews  \
0                0                0               238                  2   
1                0               11               286                  6   
2               42               56                56                 40   
3               52               82                82                 44   
4               54               84               353                 47   

   calculated_host_listings_count  
0                              13  
1                              13  
2                               4  
3                               4  
4                              16

In [5]:
X = dataset.drop('id', 1)

X.head()


accommodates  bathrooms  bedrooms  beds  price  guests_included  \
0             2        1.0         1     1   1523                2   
1             2        1.0         1     1    914                1   
2             3        1.0         1     1   1523                1   
3             2        1.0         1     1   1279                1   
4             4        4.0         1     4    396                1   

   extra_people  minimum_nights  maximum_nights  availability_30  \
0             0               7             365                0   
1             0              30             365                0   
2           244               2             365               18   
3           244               1             365               22   
4           350               1              90               26   

   availability_60  availability_90  availability_365  number_of_reviews  \
0                0                0               238                  2   
1                0               11               286                  6   
2               42               56                56                 40   
3               52               82                82                 44   
4               54               84               353                 47   

   calculated_host_listings_count  
0                              13  
1                              13  
2                               4  
3                               4  
4                              16

In [15]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()  
X_train = sc.fit_transform(dataset)  

X_train

array([[-2.30431635, -0.62531604, -0.34117854, ...,  0.39342733,
        -0.60312427,  0.22604454],
       [-2.30431609, -0.62531604, -0.34117854, ...,  0.76652263,
        -0.51287398,  0.22604454],
       [-2.30349026, -0.28842068, -0.34117854, ..., -1.0212257 ,
         0.25425351, -0.47862181],
       ...,
       [ 1.50986531, -0.28842068, -0.34117854, ..., -0.82690523,
        -0.64824942, -0.63521433],
       [ 1.50996915,  0.04847469, -0.34117854, ..., -0.11180589,
        -0.64824942, -0.24373302],
       [ 1.51077249, -0.62531604, -0.34117854, ...,  1.36502968,
        -0.64824942, -0.71351059]])

In [16]:
import numpy as np
cov_mat = np.cov(X_train.T) 
print('NumPy covariance matrix: \n%s' %cov_mat_numpy)

NumPy covariance matrix: 
[[ 1.00011086e+00  7.47045756e-03 -6.17139712e-02 -1.17823591e-02
  -2.71405273e-02 -6.64477680e-03  5.59307323e-02 -3.18866038e-02
  -3.49255924e-02 -1.08304448e-02 -1.40966226e-02  1.35984694e-03
   1.18110128e-02 -9.47866898e-02 -4.03904048e-01 -4.10490329e-02]
 [ 7.47045756e-03  1.00011086e+00  4.25179493e-01  5.46096704e-01
   6.90804075e-01  6.14689857e-02  5.63340051e-01  2.15591577e-01
  -3.75173849e-02  2.88390161e-02  6.78172126e-02  5.77936173e-02
   5.63903519e-02  1.09898334e-01  3.42839541e-02  3.17193270e-02]
 [-6.17139712e-02  4.25179493e-01  1.00011086e+00  3.07355102e-01
   5.74314982e-01  5.20121092e-03  1.15689165e-01  5.16304208e-02
  -1.96351746e-02  5.90997012e-02  1.62891161e-01  1.36341791e-01
   1.23559374e-01  1.35560018e-01 -9.95116187e-02  1.57096128e-01]
 [-1.17823591e-02  5.46096704e-01  3.07355102e-01  1.00011086e+00
   4.25297772e-01  6.79719789e-02  4.19390647e-01  1.03075217e-01
  -5.54617277e-03  4.15960351e-02 -1.37575640e-

In [17]:
eig_vals, eig_vecs = np.linalg.eig(cov_mat)

print('Eigenvectors \n%s' %eig_vecs)
print('\nEigenvalues \n%s' %eig_vals)

Eigenvectors 
[[-6.54233724e-03  1.54190750e-02  6.95096749e-01 -5.67802119e-03
   7.42792780e-02  1.60745987e-01 -2.77562668e-02 -8.28324000e-02
   4.57289424e-01 -3.06656957e-02 -1.08551298e-01 -1.66532181e-01
  -1.52904688e-01  1.74210520e-02  4.49409420e-01 -4.81342157e-02]
 [ 2.24460742e-01 -4.71647955e-01 -7.36213526e-03 -5.38344539e-04
   3.23895427e-03  7.56429973e-02  7.45787075e-01  3.36623698e-01
  -1.02669282e-01 -3.09868693e-02  2.13178151e-02 -5.50437139e-02
  -7.63118706e-02  1.67940095e-02  1.74121926e-01  2.13412658e-02]
 [ 2.35163875e-01 -2.79112983e-01  4.98430559e-02  7.39187769e-05
  -5.09298569e-03 -3.19017379e-01  9.28739842e-02 -6.53944305e-01
   1.79680111e-02 -1.49277891e-01  1.86329174e-01  2.70948403e-01
   2.04610496e-01 -3.62675908e-01  1.28704175e-01 -7.44340754e-02]
 [ 1.38594258e-01 -4.07782786e-01  2.26097564e-02 -1.62511052e-03
   7.86763574e-04  4.65763495e-02 -9.90379770e-02 -3.22333687e-02
   5.05435677e-01  4.36427874e-02  7.29214462e-02 -6.954861

In [18]:
cor_mat = np.corrcoef(X_train.T)

eig_vals, eig_vecs = np.linalg.eig(cor_mat)

print('Eigenvectors \n%s' %eig_vecs)
print('\nEigenvalues \n%s' %eig_vals)

Eigenvectors 
[[-6.54233724e-03  1.54190750e-02  6.95096749e-01 -5.67802119e-03
   7.42792780e-02 -1.60745987e-01 -2.77562668e-02 -8.28324000e-02
   4.57289424e-01 -3.06656957e-02 -1.08551298e-01 -1.66532181e-01
  -1.52904688e-01  1.74210520e-02  4.49409420e-01 -4.81342157e-02]
 [ 2.24460742e-01 -4.71647955e-01 -7.36213526e-03 -5.38344539e-04
   3.23895427e-03 -7.56429973e-02  7.45787075e-01  3.36623698e-01
  -1.02669282e-01 -3.09868693e-02  2.13178151e-02 -5.50437139e-02
  -7.63118706e-02  1.67940095e-02  1.74121926e-01  2.13412658e-02]
 [ 2.35163875e-01 -2.79112983e-01  4.98430559e-02  7.39187769e-05
  -5.09298569e-03  3.19017379e-01  9.28739842e-02 -6.53944305e-01
   1.79680111e-02 -1.49277891e-01  1.86329174e-01  2.70948403e-01
   2.04610496e-01 -3.62675908e-01  1.28704175e-01 -7.44340754e-02]
 [ 1.38594258e-01 -4.07782786e-01  2.26097564e-02 -1.62511052e-03
   7.86763574e-04 -4.65763495e-02 -9.90379770e-02 -3.22333687e-02
   5.05435677e-01  4.36427874e-02  7.29214462e-02 -6.954861

In [19]:
from sklearn.decomposition import PCA

pca = PCA()  
X_train = pca.fit_transform(X_train)  

X_train

array([[-2.54614213,  0.33030417,  1.07824416, ...,  0.07536179,
         0.11657876,  0.04103145],
       [-2.32801817, -0.09340613,  1.21382406, ..., -0.06611719,
        -0.07582977, -0.14577859],
       [-0.6502645 , -0.7464731 ,  1.65517905, ..., -0.31088006,
        -0.02399796,  0.16258189],
       ...,
       [ 0.97930551, -1.11897342, -1.49038888, ...,  0.15539353,
         0.37145673,  0.11241222],
       [ 0.94424083, -1.75579595, -1.41986521, ..., -0.37794995,
         0.06021789, -0.02286355],
       [ 1.28860514, -2.07603748, -1.19513007, ...,  0.08102959,
         0.23676064, -0.0106764 ]])

In [20]:
explained_variance = pca.explained_variance_ratio_  
explained_variance

array([0.21750195, 0.17074506, 0.08834533, 0.07804523, 0.0650102 ,
       0.06278819, 0.06007744, 0.05454357, 0.05083994, 0.03741871,
       0.03675995, 0.02991151, 0.02582949, 0.01461535, 0.0065853 ,
       0.00098278])

In [21]:
from sklearn.decomposition import PCA

pca = PCA(n_components=1)  
X_train = pca.fit_transform(X_train)  

X_train

array([[-2.54614355],
       [-2.32801902],
       [-0.65026557],
       ...,
       [ 0.97930542],
       [ 0.94424078],
       [ 1.28860591]])

In [22]:
explained_variance = pca.explained_variance_ratio_  
explained_variance

array([0.21750195])