<a href="https://colab.research.google.com/github/Kzis/BADS4002/blob/master/pca.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import pandas as pd

dataset = pd.read_csv('AirBNB_Taipei_listings_clean_missing.csv').drop('id', 1)

dataset.head()


accommodates  bathrooms  bedrooms  beds  price  guests_included  \
0             2        1.0         1     1   1523                2   
1             2        1.0         1     1    914                1   
2             3        1.0         1     1   1523                1   
3             2        1.0         1     1   1279                1   
4             4        4.0         1     4    396                1   

   extra_people  minimum_nights  maximum_nights  availability_30  \
0             0               7             365                0   
1             0              30             365                0   
2           244               2             365               18   
3           244               1             365               22   
4           350               1              90               26   

   availability_60  availability_90  availability_365  number_of_reviews  \
0                0                0               238                  2   
1                0               11               286                  6   
2               42               56                56                 40   
3               52               82                82                 44   
4               54               84               353                 47   

   calculated_host_listings_count  
0                              13  
1                              13  
2                               4  
3                               4  
4                              16

In [47]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()  
X_train = sc.fit_transform(dataset)  

print(len(X_train[0]))
X_train

15


array([[-0.62531604, -0.34117854, -0.25640569, ...,  0.39342733,
        -0.60312427,  0.22604454],
       [-0.62531604, -0.34117854, -0.25640569, ...,  0.76652263,
        -0.51287398,  0.22604454],
       [-0.28842068, -0.34117854, -0.25640569, ..., -1.0212257 ,
         0.25425351, -0.47862181],
       ...,
       [-0.28842068, -0.34117854, -0.25640569, ..., -0.82690523,
        -0.64824942, -0.63521433],
       [ 0.04847469, -0.34117854, -1.31066079, ..., -0.11180589,
        -0.64824942, -0.24373302],
       [-0.62531604, -0.34117854, -0.25640569, ...,  1.36502968,
        -0.64824942, -0.71351059]])

In [48]:
import numpy as np
cov_mat = np.cov(X_train.T) 
print('NumPy covariance matrix: \n%s' %cov_mat_numpy)

NumPy covariance matrix: 
[[ 1.00011086e+00  7.47045756e-03 -6.17139712e-02 -1.17823591e-02
  -2.71405273e-02 -6.64477680e-03  5.59307323e-02 -3.18866038e-02
  -3.49255924e-02 -1.08304448e-02 -1.40966226e-02  1.35984694e-03
   1.18110128e-02 -9.47866898e-02 -4.03904048e-01 -4.10490329e-02]
 [ 7.47045756e-03  1.00011086e+00  4.25179493e-01  5.46096704e-01
   6.90804075e-01  6.14689857e-02  5.63340051e-01  2.15591577e-01
  -3.75173849e-02  2.88390161e-02  6.78172126e-02  5.77936173e-02
   5.63903519e-02  1.09898334e-01  3.42839541e-02  3.17193270e-02]
 [-6.17139712e-02  4.25179493e-01  1.00011086e+00  3.07355102e-01
   5.74314982e-01  5.20121092e-03  1.15689165e-01  5.16304208e-02
  -1.96351746e-02  5.90997012e-02  1.62891161e-01  1.36341791e-01
   1.23559374e-01  1.35560018e-01 -9.95116187e-02  1.57096128e-01]
 [-1.17823591e-02  5.46096704e-01  3.07355102e-01  1.00011086e+00
   4.25297772e-01  6.79719789e-02  4.19390647e-01  1.03075217e-01
  -5.54617277e-03  4.15960351e-02 -1.37575640e-

In [49]:
eig_vals, eig_vecs = np.linalg.eig(cov_mat)

print('Eigenvectors \n%s' %eig_vecs)
print('\nEigenvalues \n%s' %eig_vals)

Eigenvectors 
[[ 2.24402149e-01 -4.71892208e-01 -9.81009067e-04  1.29020438e-02
   7.43937578e-01 -7.84004391e-02  3.31920158e-01  2.19246830e-01
   3.73187763e-02 -3.38657473e-02 -1.91354278e-02  5.59000793e-02
   2.69357282e-02 -3.67759842e-02 -2.92491320e-02]
 [ 2.35004202e-01 -2.78918042e-01  5.79451739e-04 -1.33411480e-02
   9.77314718e-02  3.27481635e-01 -6.44415561e-01  1.07129558e-02
  -5.93381770e-02  9.38882651e-02 -2.28413807e-01 -1.44908447e-02
   1.09564027e-01  5.01473097e-01  8.01196899e-02]
 [ 1.38523232e-01 -4.07944693e-01 -1.34464432e-03 -4.59316280e-03
  -9.60637540e-02 -3.62559232e-02  4.16030591e-04 -7.99690321e-01
  -7.29133646e-02  4.17814659e-02  2.73884467e-02  1.02467366e-01
   9.99453378e-02 -2.05879361e-01 -3.05998198e-01]
 [ 2.64702328e-01 -3.97233917e-01 -3.75645128e-03 -3.67928620e-02
  -5.98855578e-01  1.75333724e-01  4.95729377e-01  2.25917864e-01
   8.50192687e-02  1.95810669e-02 -1.55803656e-01  2.29337420e-02
   7.37129824e-02  1.92787779e-01  9.7982

In [50]:
cor_mat = np.corrcoef(X_train.T)

eig_vals, eig_vecs = np.linalg.eig(cor_mat)

print('Eigenvectors \n%s' %eig_vecs)
print('\nEigenvalues \n%s' %eig_vals)

Eigenvectors 
[[ 2.24402149e-01 -4.71892208e-01 -9.81009067e-04  1.29020438e-02
   7.43937578e-01 -7.84004391e-02  3.31920158e-01  2.19246830e-01
   3.73187763e-02 -3.38657473e-02 -1.91354278e-02  5.59000793e-02
   2.69357282e-02 -3.67759842e-02 -2.92491320e-02]
 [ 2.35004202e-01 -2.78918042e-01  5.79451739e-04 -1.33411480e-02
   9.77314718e-02  3.27481635e-01 -6.44415561e-01  1.07129558e-02
  -5.93381770e-02  9.38882651e-02 -2.28413807e-01 -1.44908447e-02
   1.09564027e-01  5.01473097e-01  8.01196899e-02]
 [ 1.38523232e-01 -4.07944693e-01 -1.34464432e-03 -4.59316280e-03
  -9.60637540e-02 -3.62559232e-02  4.16030591e-04 -7.99690321e-01
  -7.29133646e-02  4.17814659e-02  2.73884467e-02  1.02467366e-01
   9.99453378e-02 -2.05879361e-01 -3.05998198e-01]
 [ 2.64702328e-01 -3.97233917e-01 -3.75645128e-03 -3.67928620e-02
  -5.98855578e-01  1.75333724e-01  4.95729377e-01  2.25917864e-01
   8.50192687e-02  1.95810669e-02 -1.55803656e-01  2.29337420e-02
   7.37129824e-02  1.92787779e-01  9.7982

In [51]:
from sklearn.decomposition import PCA

pca = PCA()  
X_train = pca.fit_transform(X_train)  

X_train

array([[-2.56073001e+00,  2.96063569e-01, -7.75753083e-01, ...,
         1.53057509e-01,  3.10351146e-01,  5.46671691e-02],
       [-2.34287929e+00, -1.28840006e-01, -9.77438606e-01, ...,
         9.04971510e-04,  9.99884488e-02, -1.32656596e-01],
       [-6.65158271e-01, -7.82224724e-01,  7.08658955e-01, ...,
        -2.46737611e-01,  1.48380635e-01,  1.75214801e-01],
       ...,
       [ 9.90400811e-01, -1.09233623e+00,  6.41984928e-01, ...,
         1.34057539e-01,  2.97782606e-01,  1.05502360e-01],
       [ 9.55210672e-01, -1.73015578e+00, -3.04417525e-01, ...,
        -4.03380086e-01, -1.44427632e-02, -2.89785345e-02],
       [ 1.29942247e+00, -2.05106692e+00,  9.11906049e-01, ...,
         4.85112937e-02,  1.42322214e-01, -1.84772329e-02]])

In [52]:
explained_variance = pca.explained_variance_ratio_  
explained_variance

array([0.23199521, 0.18210222, 0.08398087, 0.07055733, 0.06914349,
       0.06602464, 0.06079036, 0.05462341, 0.0540158 , 0.03990569,
       0.03528236, 0.0276418 , 0.01561598, 0.00727093, 0.00104991])

In [53]:
from sklearn.decomposition import PCA

pca = PCA(n_components=1)  
X_train = pca.fit_transform(X_train)  

X_train

array([[-2.56073015],
       [-2.34287932],
       [-0.66515822],
       ...,
       [ 0.99040084],
       [ 0.95521081],
       [ 1.29942243]])

In [54]:
explained_variance = pca.explained_variance_ratio_  
explained_variance

array([0.23199521])